site_name: ChadMusic

theme:
  name: material
  favicon: assets/deejaytreefiddy.ico
  logo: assets/deejaytreefiddy.ico
  palette:
    primary: blue
    accent: blue
  features:
    - content.tooltips
    - navigation.sections
    - navigation.top
    - navigation.prune
    - navigation.indexes
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_name: 200percentmicky/chadmusic
repo_url: https://github.com/200percentmicky/chadmusic

nav:
  - Welcome: 'index.md'
  - Changelog: 'changelog.md'
  - Commands: 'commands.md'
  - Setup:
    - 'Getting Started': 'installation/getting_started.md'
    - 'Installing Node.js': 'installation/install_node.md'
    - 'Installing git': 'installation/install_git.md'
    - 'Downloading FFmpeg': 'installation/install_ffmpeg.md'
    - 'Creating your bot': 'installation/creating_app.md'
    - 'Cloning the bot': 'installation/cloning_the_bot.md'
    - 'Installing Dependencies': 'installation/install_packages.md'
    - 'Configuring the bot': 'installation/configuration.md'
    - 'Customizing the bot': 'installation/customization.md'
    - 'Starting the bot': 'installation/starting_the_bot.md'