site_name: ChadMusic

theme:
  name: material
  favicon: assets/deejaytreefiddy.ico
  logo: assets/deejaytreefiddy.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Lights on! Click to toggle.
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Lights off... Click to toggle.

  features:
    - content.tooltips
    - content.code.copy
    - navigation.sections
    - navigation.top
    - navigation.prune
    - navigation.path
    - navigation.indexes
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/badge.css

repo_name: 200percentmicky/chadmusic
repo_url: https://github.com/200percentmicky/chadmusic

nav:
  - Home: 'index.md'
  - Changelog: 'changelog.md'
  - Commands: 'commands.md'
  - Supported Sites: 'supported_sites.md'
  - Setup:
    - 'Getting Started': 'setup/getting_started.md'
    - '1. Installing Node.js': 'setup/install_node.md'
    - '2. Installing git': 'setup/install_git.md'
    - '3. Downloading FFmpeg': 'setup/install_ffmpeg.md'
    - '4. Creating your bot': 'setup/creating_app.md'
    - '5. Cloning the bot': 'setup/cloning_the_bot.md'
    - '6. Installing Packages': 'setup/install_packages.md'
    - '7. Starting the bot': 'setup/starting_the_bot.md'
  - Configuration:
    - 'Cookies': 'configuration/cookies.md'
    - 'Customization': 'configuration/customization.md'
    - 'Environment Variables': 'configuration/env_variables.md'