name: build
on:
  push:
    branches:
      - main
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-versions: ['18.x', '20.x']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        name: Installing Yarn
      - run: npm i -g yarn
        name: Installing Dependencies
      - run: npm ci
      - run: npm run build --if-present
